open-mpi/ompi-scripts

jenkins/open-mpi-build-script.sh
The sed regexp is a bit challenging to make portable (e.g., what works
on Linux may not work in OS X / BSDs).  So just switch to Perl,
because Perl's regexps are nicely uniform across platforms.
=> jenkins: Use a perl regexp for the mpirun versio

nightly-tarball/Builder.py
GNU md5sum and sha1sum output the checksum and then the filename.
Hence, the Perl MTT client expects the data in that order.
=> Builder.py: reverse the order of filename/checksum

jenkins/customize-ami.sh
The S3 release uploader needs some Python packages
not in the default install.  Add them to the AMIs
used in building releases.
=> jenkins: Add Python Boto and Mock to amis

jenkins/customize-ami.sh
The AMIs built in December included the 32 bit packages, but
apparently the build script in git never included them.  Sigh.
=> jenkins: Include 32 bit builds on Ubuntu AMI

dist/upload-release-to-s3.py
There was an error in the conditional to determine if the
upload-release-to-s3 script needed to auto-detect any of the
configuration options (project, branch, version, date).  This
commit fixes that logic so that the script works even when
all four arguments aren't specified.
tl;dr: "or", not "and"
=> dist upload: fix conditional to choose autodetect

administrative/wait-for-pr-ci-completion.py
As the script name implies, wait for a Github PR's CI to complete.
This script does no notification; it just waits -- when the CI
completes, this script completes.  You'll typically want to execute
another command after this script completes, for example:
```
$ ./wait-for-pr-ci-completion.py \
--pr https://github.com/open-mpi/ompi/pull/5731; \
pushover CI for PR5731 is done
```
where `pushover` is a script I use to send push notifications to my
phone.
See the comments at the beginning of this script to see its
requirements and how to use it.
This script may get copied out of the Open MPI script repo, so I took
the liberty of including the license in the file.
Signed-off-by: Jeff Squyres <jeff@squyres.com>
-----
Here's a sample output from running this script:
```
$ …
```
=> wait-for-pr-ci-completion.py: wait for Github PR CI

nightly-tarball/Builder.py
Publish sha256 hashes for new nightly tarballs, as part of
supporting stronger hashes (open-mpi/ompi-www#255).  Continue
publishing md5 and sha1 hashes, to avoid breaking consumers
of the existing hashes.
=> nightly: Publish sha256 hashes

jenkins/whitespace-checker.sh
In order to prevent violations of the coding style in ompi it was
decided to check any future PRs for white space violations. This script
checks whether a certain commit range has introduced a tab character.
See open-mpi/ompi#6831 for details.
Signed-off-by: guserav <erik.zeiske@hpe.com>
=> Add script to test for tabs in commit range

nightly-tarball/Builder.py
Open MPI now uses submodules for some components (hwloc, with more
to follow shortly).  The nightly builder needs to pull all relevant
submodules in the repository for a build to succeed.
=> nightly: Properly handle submodules

jenkins/open-mpi-build-script.sh
PRRTE only accepts --hostfile (not -hostfile).
=> jenkins: "mpirun -hostfile" is no longer accepted

jenkins/open-mpi-build-script.sh
Recent commits require pandoc for generating man pages.  Not all
distros have pandoc in the repositories, so add support for
disabling generating man pages if pandoc is not found.
=> jenkins: Add pandoc handling to CI

dist/upload-release-to-s3.py, dist/uploadutils.py
With Ubuntu 20.04 only supporting Python 3, it is time
to make all our code support either Python 2 or Python 3.
Start with the uploader script.
=> dist: Update uploader to support Python 3

dist/uploadutils.py
Update the script that is used by Open MPI (through the tarball
Jenkins job) and hwloc (manually) to publish sha256 hashes in
addition to the md5 and sha1 hashes.  The Open MPI web site has
already been updated to publish the hash if it is available and
has been publishing sha256 hashes for nightlies for a couple of
months.
=> dist: Publish SHA256 hashes for tarballs

jenkins/open-mpi.dist.create-tarball.groovy
In building the prod/preprod configuration for Tarball Builder
jobs, I missed a place where the Prod step was pulling the
ompi-scripts repository from what was the current preprod
branch.  Rather than hard-coding the location of the
ompi-scripts repository into the script, pull it from the
job def.
=> jenkins: Pull ompi-scripts repo from job def

jenkins/open-mpi-build-script.sh
Add mapping from Compiler labels to compiler names for the
compilers found on Ubuntu 18.04 and Ubuntu 20.04 by trying
to provide a generic mapping instead of detailed names.
=> jenkins: Add support for Ubuntu 18/20 compilers

jenkins/checker.py, jenkins/commit-email-checker.py, jenkins/open-mpi.pr.command-runner.groovy, jenkins/signed-off-by-checker.py
We are trying to migrate our commit email and signed off by
checkers from PHP invoked directly from the GitHub hooks to
Jenkins jobs, so that we have retries and polling and all
that goodness.  This patch contains two pieces of that:
Groovy scripts to implement the execution part of the pipeline
job.
Changes to the previously written Python-based checks, to make
them work under Python2 and to fix some poor design choices
around arguments and output that I had made when telling Jeff
the API for the first implementation.
=> jenkins: Add commit email/signed-off-by check jobs

nightly-tarball/Builder.py
Fix s couple small Python2/Python3 compatibility issues, as
aws.open-mpi.org is now Python3 by default.
=> nightly: Update to run with Python3

dist/uploadutils.py
Fixes this error during upload:
Continue? [y/N] Traceback (most recent call last):
File "ompi-scripts/dist/upload-release-to-s3.py", line 132, in <module>
uploadutils.upload_files(s3_client, bucket_name, key_prefix,
File "/home/bgoglin/ompi-scripts/dist/uploadutils.py", line 228, in upload_files
if not __query_yes_no('Continue?', 'no'):
File "/home/bgoglin/ompi-scripts/dist/uploadutils.py", line 74, in __query_yes_no
choice = raw_input().lower()
NameError: name 'raw_input' is not defined
Signed-off-by: Brice Goglin <Brice.Goglin@inria.fr>
=> uploadutils.py: use input() instead of raw_input() for Python3

nightly-tarball/Builder.py
dict.keys() returns a dict_keys object, which is not subscritable.
Hence, if "foo" is a dict, foo.keys()[0] is a Python error.  This led
to this error occurring in the OMPI nightly builds:
```
ERROR: Coverity submission failed: 'dict_keys' object is not subscriptable
```
Instead, convert the returned dict_keys to an iterator and grab the
first item via next().
=> Builder.py: fix Coverity submission Python error

nightly-tarball/Coverity.py
Use requests.get() to download the Coverity tarball instead of urllib
(apparently urllib.urlretrieve() no longer exists...?).
=> Coverity.py: Fix download

nightly-tarball/Coverity.py
No longer need the import urllib.
=> Coverity.py: remove kruft

jenkins/autotools-patches/m4-1.4.16.patch, jenkins/autotools-patches/m4-1.4.17.patch, jenkins/autotools-patches/m4-1.4.18.patch, jenkins/customize-ami.sh, jenkins/open-mpi-autotools-build.sh, jenkins/open-mpi.dist.create-tarball.groovy, jenkins/packer.json
A bundle of Jenkins changes for your Sunday night.
1. Rework the autotools build script to be usable outside of the dist script (next stop is the nightly tarball builder)
2. Add patch files (and ability to apply patch files) for building older versions of M4 on Ubuntu 18.04 and 20.04
3. Support submodules in dist job (for 5.0 branch)
4. Update the script to build new AMIs to install pandoc everywhere.
=> Number of Jenkins changes

nightly-tarball/Builder.py
Coverity builds are not fast.  There's no reason to sit on uploading
the nightly tarball while we wait for the Coverity build to finish.
=> nightly: Upload tarball, then run coverity

administrative/annual-ompi-github-committer-review.py
- Don't list archived github repos
- Sort the repos that we do list
- Don't include "open-mpi/" in the repo name; it just makes the
spreadsheet columns wider
=> admin/annual-review: updates for 2022

jenkins/open-mpi-build-script.sh
Run the "hello" examples as singletons (just "./hello_c" with no
"mpirun").
----
@bwbarrett I figured this would add negligible time to the test, and would actually alert us when singletons break.
=> open-mpi-build-script.sh: run singletons

jenkins/open-mpi-build-script.sh
Reverts open-mpi/ompi-scripts#60
Gah!  Singletons are still broken; they're awaiting a few PRs to fix them up.  🤬 
Sooo... revert this change until everything is merged.
=> Revert "open-mpi-build-script.sh: run singletons"

jenkins/jenkins-amis.hcl
Seasonal update of AMIs.  Force Java to be version 11 or later, as that is now the minimum supported version with Jenkins.  Add start of Ubuntu 22.04 AMIs, although Packer did not successfully build them yet.
=> jenkins: Update AMIs

jenkins/open-mpi.dist.create-tarball.build-rpm.sh, jenkins/open-mpi.dist.create-tarball.groovy
This change builds and installs openmpix and prrte from the ompi tree to ensure correct versions.
Also skips building man pages if using RST documenation.
Signed-off-by: Eric Raut <eraut@amazon.com>
=> Fix Open MPI RPM build step: build and install deps

jenkins/open-mpi.coverity.tool_downloader.groovy
The coverity tools are large (1+ GiB) and change infrequently.  Create a pipeline intended to run weekly to move the tools from Coverity into S3, so that we don't pay ingress charges every time we run a job. Unfortunately, I can't find a way to authenticate to the download server to just call HEAD and get the download time (which would be the smarter option), so this will have to do.
=> Add pipeline to download coverity tools

nightly-tarball/Coverity.py
The Coverity script still used some Python2-isms in argument parsing. These didn't matter for today's Coverity runs, since the package is called as a library from the nightly builder, but is important as part of splitting nightly tarballs and Coverity.
=> Fix arg parsing in Coverity script

jenkins/open-mpi-build-script.sh
Hey @bwbarrett -- is there a reason we don't already do singletons here in the OMPI Jenkins CI build script?  This PR adds a handful of singleton runs (of hello world and ring); I can't remember if there's a reason we don't already do this...?
I know we're moving to Jenkinsfile-based runs in the near future, but we've been talking about getting better runtime CI coverage on the Tuesday call recently, and this seemed like low-hanging fruit (even if we move to Jenkinsfile soon), especially since singleton was broken recently (i.e., within Dec 2022).
---
Add singleton runs to the Open MPI Jenkins CI build script, just for slightly better runtime coverage in CI.
FYI @naughtont3
=> jenkins/ompi-build-script: add singletons

jenkins/open-mpi-build-script.sh
The CI tests on the AWS jenkins instance all run on instances with 1 core.  There's a special case in OMPI to bind to core for a 2 process run for benchmarking reasons, and this was causing failures in mapping because there aren't 2 cores on the instance.  So instead turn off binding for these small tests.
=> jenkins: Don't bind for CI tests

nightly-tarball/BuilderUtils.py
For quite a while, the build-with-autotools Open MPI nightly build on Open MPI v5.0.0 has been failing.  It turns out that upstream PMIx upgraded the version of Sphinx that it required, which ultimately caused the build failure because the Sphinx version installed on aws.open-mpi.org was too old.  Upgrading the Sphinx on aws.open-mpi.org was easy enough.
The real issue is that the failure notification email did not include enough logging output to reveal that the root cause of the build failure was the Sphinx version.  As such, this commit increases the default number of log lines included in the failure message in the email so that this particular problem, at least, will be evident in future emails.
=> BuilderUtils.py: default to more logging output
